### ISSUE TITLE
Can this repo support previous version of bazel?

### ISSUE THREAD

**Issue by JiayiFu** [vbatts/copr-build-bazel#11]
Hi, 
  I want to use this repo to install Bazel 0.24.1 in my CentOS 7. But I found this repo only support the latest version. Is there any other way which I can install a specific version of Bazel in CentOS? Thanks!

**Comment by vbatts** [comment]
@JiayiFu hey hey!
the copr infrastructure is really geared towards only the latest rpm. _but_ I make tags for the versions that I build https://github.com/vbatts/copr-build-bazel/releases
Just clone this git repo, `git checkout v0.22.0 && make rpm` of whatever version, and it should produce the rpm you need (once you install any build dependencies...)

**Comment by JiayiFu** [comment]
@vbatts I get it, thanks!
