### ISSUE TITLE
bazel-0.27.1 make rpm show this bug 

### ISSUE THREAD

**Issue by lzb-James** [vbatts/copr-build-bazel#15]
🍃  Building Bazel from scratch..find: 'src/tools/xcode-common/java/com/google/devtools/build/xcode/common': No such file or directory
find: 'src/tools/xcode-common/java/com/google/devtools/build/xcode/util': No such file or directory

how to slove it

**Comment by vbatts** [comment]
please reopen if this is still a blocker
