### ISSUE TITLE
Build for ppc64le architecture

### ISSUE THREAD

**Issue by runlevel5** [vbatts/copr-build-bazel#16]
Hi there

 I have been building from source since version 3 on Fedora 33 ppc64le and sharing the binary with friends. However I think an RPM package would be more suitable for distribution. I happen to learn that you are maintaining a COPR repo for bazel so I am writing to you in hope you could tweak the COPR build option to also produce package for ppc64le. 
 
 Many thanks in advance

**Comment by vbatts** [comment]
please reopen is this is still an issue

**Comment by runlevel5** [comment]
@vbatts great thanks
