### ISSUE TITLE
Bazel 4.2.2 not available

### ISSUE THREAD

**Issue by agro1986** [vbatts/copr-build-bazel#17]
Hi,

One of the Ethereum consensus layer prysm https://github.com/prysmaticlabs/prysm requires Bazel 4.2.2 for building its latest version. Any chance you can provide it? Specifically, I'm using https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo

Best regards

**Comment by vbatts** [comment]
sorry, just seeing this. If it is still needed please reopen.
