### ISSUE TITLE
A simple request -epel-7-armhfp

### ISSUE THREAD

**Issue by corsariovasco** [vbatts/copr-build-bazel#2]
Hi, 

Please, might we dispose a version for epel-7-armhfp?.

Thanks,

Kind regards,

**Comment by vbatts** [comment]
Oh hey?! GitHub notifications! :-/
Let me look at copr options

**Comment by vbatts** [comment]
![screenshot from 2018-12-19 16-23-25](https://user-images.githubusercontent.com/67049/50248924-958ed400-03aa-11e9-96bf-100f8e1a66e1.png)

that doesn't look to be an option of architecture.
You can buildfrom local though. Just clone this repo and run `make rpm`

**Comment by corsariovasco** [comment]
Thanks!!!
