### ISSUE TITLE
Install older versions

### ISSUE THREAD

**Issue by derfsubterfuge** [vbatts/copr-build-bazel#3]
How do I install an older version of bazel?  When I run `sudo dnf list --showduplicates bazel`, only version `0.13.0-1.fc27` comes up.

**Comment by vbatts** [comment]
Oh hmm, that may be a function of copr. You might could rebuild from an earlier commit?

**Comment by vbatts** [comment]
you can checkout c7c8690dd9494794db834c22a64ad917caf09234 and run `make rpm`
