### ISSUE TITLE
`bazel version` reports version with trailing dash, which breaks related tooling

### ISSUE THREAD

**Issue by jirkadanek** [vbatts/copr-build-bazel#5]
```
$ bazel version
Build label: 0.19.2- (@non-git)
[...]
```
The trailing `-` means that the version number is not parsed by https://github.com/zafarkhaja/jsemver/blob/1f4996ea3dab06193c378fd66fd4f8fdc8334cc6/src/main/java/com/github/zafarkhaja/semver/VersionParser.java, which in turn means Bazel is not detected by https://github.com/JetBrains/teamcity-bazel-plugin/blob/fba88c1ad8205ba57fd0090c184a072e4d5e6feb/plugin-bazel-agent/src/main/kotlin/jetbrains/buildServer/bazel/BazelToolProvider.kt.

Would it be possible to get rid of the dash?

If I use binary distribution of Bazel (the installer), I do not have this problem. I only used 0.20.0 installer, so possibly the dash was fixed in Bazel itself going from 0.19.2...

I am using  Bazel on RHEL 7.6.

**Comment by vbatts** [comment]
Oh interesting, might you open an issue on bazel repo about this?

**Comment by vbatts** [comment]
i'm really not sure. I've opened the question upstream https://groups.google.com/d/msg/bazel-dev/kecthXfgGOA/4RvDHLBrBAAJ

**Comment by jirkadanek** [comment]
Thanks, it is fixed in 27-5 package. Comparing, before and after:

```
[root@dhcp-144-231 ~]# bazel --version
[bazel FATAL src/main/cpp/blaze.cc:1327] Unknown startup option: '--version'.
  For more info, run 'bazel help startup_options'.
[root@dhcp-144-231 ~]# bazel version
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 4795ead9-b3fe-4278-a253-4df0248b5754
Build label: 0.21.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 20:53:59 2018 (1545252839)
Build timestamp: 1545252839
Build timestamp as int: 1545252839
```

```
[root@dhcp-144-231 ~]# bazel version
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.27.0
```
