### ISSUE TITLE
bazel.sh compatibility

### ISSUE THREAD

**Issue by emidln** [vbatts/copr-build-bazel#6]
The official binary installs bazel.sh as a wrapper script named bazel and the actual bazel self-extracting binary as bazel-real. This is to allow bash.sh to invoke a tools/bazel executable if it exists. Can this be added to the spec file? I think the relevant target is here: https://github.com/bazelbuild/bazel/blob/master/scripts/packages/BUILD#L108

**Comment by vbatts** [comment]
Would you like to try your hand at a PR for this?

**Comment by vbatts** [comment]
fixed with 36e6b89
