### ISSUE TITLE
Please provide more than just the most recent Bazel release

### ISSUE THREAD

**Issue by JonathanRRogers** [vbatts/copr-build-bazel#7]
I just spent several hours trying to figure out why a project that worked a couple of months ago wouldn't build. Eventually, I discovered that Bazel 0.21 broke a bunch of stuff. I tried to install an earlier version from the COPR repository but there aren't any. I was able to install Bazel 0.19.1 using an installer script from the project, but an RPM would be preferable. Also, since the Bazel project apparently can't be trusted not to break things with a minor release, it would be great if a new RPM package were created for a backward-incompatible release.

**Comment by vbatts** [comment]
This is more problematic than it seems. Copr purges and garbage collects. For hosts that you keep around, but run periodic updates on, I would investigate yum or dnf `versionlock` plugins. Upstream has received this kind of feedback, but while they are in a pre-1.0, they are not making backwards compatible promises.
As for me maintaining that, it is more than I can do. It is best effort for me to just get latest build posted.
I do have tags on this repo, so you can `git checkout` that release, and run `make rpm` to build a prior version for yourself.

**Comment by JonathanRRogers** [comment]
OK, 

> This is more problematic than it seems. Copr purges and garbage collects. For hosts that you keep around, but run periodic updates on, I would investigate yum or dnf `versionlock` plugins. Upstream has received this kind of feedback, but while they are in a pre-1.0, they are not making backwards compatible promises.
> As for me maintaining that, it is more than I can do. It is best effort for me to just get latest build posted.
> I do have tags on this repo, so you can `git checkout` that release, and run `make rpm` to build a prior version for yourself.

Thanks for trying. I'm further convinced to stay as far away from bazel as I can in the future.
